name: Generate Unsplash Photo URLs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run Unsplash script
        env:
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: |
          python unsplash_locations_to_photos.py

      - name: Upload generated CSV
        uses: actions/upload-artifact@v4
        with:
          name: routes-with-photos
          path: all-global-routes-with-photos.csv
